### ISSUE TITLE
感谢作者的工作，mAP过低问题

### ISSUE THREAD

**Issue by hlf1996** [DetectionTeamUCAS/RetinaNet_Tensorflow#4]
从tensorboard可以看到loss已经收敛而且检测已经较为准确，但是运行eval.py的时候AP值总是 太低。
diningtable|| Recall: 0.529126213592233 || Precison: 0.00022013086679053236|| AP: 0.0001828368941026608
cls : cat|| Recall: 0.5810055865921788 || Precison: 0.0004200348548153563|| AP: 0.00044216188859826756
cls : person|| Recall: 0.1707155477031802 || Precison: 0.0015611430879531455|| AP: 0.00029018684808718506
cls : bus|| Recall: 0.19248826291079812 || Precison: 8.279516476237788e-05|| AP: 2.628493925550538e-05
cls : sofa|| Recall: 0.5188284518828452 || Precison: 0.00025046608911341063|| AP: 0.00031115428603248417
cls : chair|| Recall: 0.11243386243386243 || Precison: 0.00017167347301494973|| AP: 5.969452499291218e-05
cls : motorbike|| Recall: 0.3230769230769231 || Precison: 0.00021203982309820474|| AP: 0.00017035599639468496
cls : bicycle|| Recall: 0.24629080118694363 || Precison: 0.00016761006225805085|| AP: 7.167836330506075e-05
cls : dog|| Recall: 0.5419222903885481 || Precison: 0.0005351481249621357|| AP: 0.0005161055134681762
cls : boat|| Recall: 0.16730038022813687 || Precison: 8.885406527542741e-05|| AP: 2.0466377579083363e-05
cls : cow|| Recall: 0.2786885245901639 || Precison: 0.00013732130560250734|| AP: 3.748752712792251e-05
cls : horse|| Recall: 0.3936781609195402 || Precison: 0.0002766581313257781|| AP: 0.00021959843525756463
cls : pottedplant|| Recall: 0.08125 || Precison: 7.875780762496744e-05|| AP: 8.623173773479285e-06
cls : aeroplane|| Recall: 0.2596491228070175 || Precison: 0.0001494345718901454|| AP: 5.999370564097025e-05
cls : train|| Recall: 0.36524822695035464 || Precison: 0.0002079976090371932|| AP: 0.00013058891760991555
cls : bird|| Recall: 0.26143790849673204 || Precison: 0.00024232780085501325|| AP: 7.989153674825875e-05
cls : tvmonitor|| Recall: 0.09090909090909091 || Precison: 5.6543381900059574e-05|| AP: 5.514559619085733e-06
cls : sheep|| Recall: 0.22727272727272727 || Precison: 0.00011106780588578595|| AP: 3.0393658667055707e-05
cls : bottle|| Recall: 0.0511727078891258 || Precison: 4.846644102845788e-05|| AP: 4.44962991130219e-06
cls : car|| Recall: 0.13655287260616153 || Precison: 0.000331216777341541|| AP: 9.944533801359351e-05
mAP is : 0.00013834560570925842

请问可能是什么原因

**Comment by yangxue0827** [comment]
额，我重新下载训练了好几遍都没啥问题。你这个我不好判断，可能是环境。 @hlf1996
