### ISSUE TITLE
train.py and multi_gpu_train.py

### ISSUE THREAD

**Issue by g18tka17** [DetectionTeamUCAS/RetinaNet_Tensorflow#5]
hello, Mr.yang. i meet a problem.
when i use train.py to training my dataset, it's mAP always lower than using multi_gpu_train.py.
so, can you tell me that's why?  what is the train.py file for? how to use train,py file can achieve the same result with use multi_gpu_train.py.
thank you.

**Comment by g18tka17** [comment]
and i notice that the the training total loss using multi_gpu_train.py can be reduced to about 0.1, but the training using train.py will only drop to 0.4 (both are training 200k times).  So if I want to use train.py to achieve the effect of multi_gpu_train.py , should I increase the number or adjust the parameters?

**Comment by yangxue0827** [comment]
I'm curious why you don't use multi_gpu_train.py. @g18tka17

**Comment by g18tka17** [comment]
In fact, I was interested in tensorflow multi-core GPU programming, and I want to try to understand their differences. Actually I only have one 1080Ti, so I produce a little curious about the different results from these two files.@yangxue0827

**Comment by yangxue0827** [comment]
I am not very clear, but the performance of these two scripts in the [FPN ](https://github.com/DetectionTeamUCAS/RFPN_Tensorflow)project is the same (COCO dataset).
@g18tka17
