### ISSUE TITLE
mAP of Resnet50 backbone

### ISSUE THREAD

**Issue by chenbiaolong** [DetectionTeamUCAS/RetinaNet_Tensorflow#6]
在你的readme里Resnet50 的mAP 为33.4，但我同时注意到在你的[配置文件注释](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow/blob/master/libs/configs/COCO/cfgs_res50_coco_1x_v1.py#L16)里resnet50_v1指标只有31.5，后面的配置文件都使用的是Resnet50-v1d.

我的问题是目前你的复现resnet50（原始MSRA版本）的指标是多少？根据你的配置文件注释，从resnet50-v1改成resnet50-v1d可以从31.5提升到34.3?

**Comment by yangxue0827** [comment]
v1到v1d是31.5到32.7，加了梯度扩大和裁剪之后提升到33.4，batch size调整到2之后提升到34.3。具体参数你可以对比几个cfgs的差别。

**Comment by yangxue0827** [comment]
原版MSRA是什么意思？

**Comment by chenbiaolong** [comment]
就是何凯明最初没有经过修改的Resnet50-v1，所以33.4是resnet50-v1经过梯度扩大和裁剪达到的？能否给出resnet50-v1达到33.4时的配置文件？因为论文的resnet50-v1均使用的原始版本的resnet50，resnet50-v1d虽然只是小修改，但毕竟也是提升了性能，和论文的resnet50比较指标不大公平

**Comment by yangxue0827** [comment]
v1加上梯度的处理和bs的增大，最终能有多少我没跑过，你可以把34.3的配置文件里backbone名字换一下就行。还有就是这个不影响消融实验吧，因为都是用的同一个backbone，而且你要考虑到原论文600的配置点数是34。

**Comment by chenbiaolong** [comment]
实际上我现在也在复现指标，但使用tensorflow的resnet50的checkpoint finetune得到的指标和你第一版本的指标差不多(31左右)，而且我注意到pytorch的实现中(mmdetection)其实并没有使用类似于你用到的梯度扩大等trick就能达到比较好的指标。所以我在怀疑是否是checkpoint的问题。因此才问你使用原始的resnet50v1 finetune最好的指标能达到多少.我大致明白你的实验了，感谢回答，我后面再做一些实验。

**Comment by yangxue0827** [comment]
mmdet的retina用了梯度扩大裁剪的

**Comment by chenbiaolong** [comment]
ok,我把这部分内容加上做一下实验，谢谢回复
